import { $dCubeScanIcon } from './3d-cube-scan';
import { $dRotateIcon } from './3d-rotate';
import { $dSquareIcon } from './3d-square';
import { box1Icon } from './box-1';
import { boxAddIcon } from './box-add';
import { boxRemoveIcon } from './box-remove';
import { boxSearchIcon } from './box-search';
import { boxTickIcon } from './box-tick';
import { boxTimeIcon } from './box-time';
import { boxIcon } from './box';
import { convert3DCubeIcon } from './convert-3d-cube';
import { group1Icon } from './group-1';
import { groupIcon } from './group';
import { truckRemoveIcon } from './truck-remove';
import { truckTickIcon } from './truck-tick';
import { truckTimeIcon } from './truck-time';
export const deliveryIcons = [$dCubeScanIcon, $dRotateIcon, $dSquareIcon, box1Icon, boxAddIcon, boxRemoveIcon, boxSearchIcon, boxTickIcon, boxTimeIcon, boxIcon, convert3DCubeIcon, group1Icon, groupIcon, truckRemoveIcon, truckTickIcon, truckTimeIcon];
