import { awardIcon } from './award';
import { book1Icon } from './book-1';
import { bookIcon } from './book';
import { bookmark2Icon } from './bookmark-2';
import { bookmarkIcon } from './bookmark';
import { briefcaseIcon } from './briefcase';
import { brifecaseCrossIcon } from './brifecase-cross';
import { brifecaseTickIcon } from './brifecase-tick';
import { brifecaseTimerIcon } from './brifecase-timer';
import { calculatorIcon } from './calculator';
import { clipboardIcon } from './clipboard';
import { giftIcon } from './gift';
import { note2Icon } from './note-2';
import { noteIcon } from './note';
import { teacherIcon } from './teacher';
export const schoolLearningIcons = [awardIcon, book1Icon, bookIcon, bookmark2Icon, bookmarkIcon, briefcaseIcon, brifecaseCrossIcon, brifecaseTickIcon, brifecaseTimerIcon, calculatorIcon, clipboardIcon, giftIcon, note2Icon, noteIcon, teacherIcon];
