import { callAddIcon } from './call-add';
import { callCallingIcon } from './call-calling';
import { callIncomingIcon } from './call-incoming';
import { callMinusIcon } from './call-minus';
import { callOutgoingIcon } from './call-outgoing';
import { callReceivedIcon } from './call-received';
import { callRemoveIcon } from './call-remove';
import { callSlashIcon } from './call-slash';
import { callIcon } from './call';
export const callIcons = [callAddIcon, callCallingIcon, callIncomingIcon, callMinusIcon, callOutgoingIcon, callReceivedIcon, callRemoveIcon, callSlashIcon, callIcon];
