import { searchFavorite1Icon } from './search-favorite-1';
import { searchFavoriteIcon } from './search-favorite';
import { searchNormal1Icon } from './search-normal-1';
import { searchNormalIcon } from './search-normal';
import { searchStatus1Icon } from './search-status-1';
import { searchStatusIcon } from './search-status';
import { searchZoomIn1Icon } from './search-zoom-in-1';
import { searchZoomInIcon } from './search-zoom-in';
import { searchZoomOut1Icon } from './search-zoom-out-1';
import { searchZoomOutIcon } from './search-zoom-out';
export const searchIcons = [searchFavorite1Icon, searchFavoriteIcon, searchNormal1Icon, searchNormalIcon, searchStatus1Icon, searchStatusIcon, searchZoomIn1Icon, searchZoomInIcon, searchZoomOut1Icon, searchZoomOutIcon];
