import { bag2Icon } from './bag-2';
import { bagCross1Icon } from './bag-cross-1';
import { bagCrossIcon } from './bag-cross';
import { bagHappyIcon } from './bag-happy';
import { bagTick2Icon } from './bag-tick-2';
import { bagTickIcon } from './bag-tick';
import { bagTimerIcon } from './bag-timer';
import { bagIcon } from './bag';
import { barcodeIcon } from './barcode';
import { shopAddIcon } from './shop-add';
import { shopRemoveIcon } from './shop-remove';
import { shopIcon } from './shop';
import { shoppingBagIcon } from './shopping-bag';
import { shoppingCartIcon } from './shopping-cart';
export const shopIcons = [bag2Icon, bagCross1Icon, bagCrossIcon, bagHappyIcon, bagTick2Icon, bagTickIcon, bagTimerIcon, bagIcon, barcodeIcon, shopAddIcon, shopRemoveIcon, shopIcon, shoppingBagIcon, shoppingCartIcon];
