import { calendar1Icon } from './calendar-1';
import { calendar2Icon } from './calendar-2';
import { calendarAddIcon } from './calendar-add';
import { calendarCircleIcon } from './calendar-circle';
import { calendarEditIcon } from './calendar-edit';
import { calendarRemoveIcon } from './calendar-remove';
import { calendarSearchIcon } from './calendar-search';
import { calendarTickIcon } from './calendar-tick';
import { calendarIcon } from './calendar';
import { clockIcon } from './clock';
import { securityTimeIcon } from './security-time';
import { timer1Icon } from './timer-1';
import { timerPauseIcon } from './timer-pause';
import { timerStartIcon } from './timer-start';
import { timerIcon } from './timer';
export const timeIcons = [calendar1Icon, calendar2Icon, calendarAddIcon, calendarCircleIcon, calendarEditIcon, calendarRemoveIcon, calendarSearchIcon, calendarTickIcon, calendarIcon, clockIcon, securityTimeIcon, timer1Icon, timerPauseIcon, timerStartIcon, timerIcon];
