import { candle2Icon } from './candle-2';
import { candleIcon } from './candle';
import { category2Icon } from './category-2';
import { categoryIcon } from './category';
import { menuIcon } from './menu';
import { more2Icon } from './more-2';
import { moreIcon } from './more';
import { setting2Icon } from './setting-2';
import { setting3Icon } from './setting-3';
import { setting4Icon } from './setting-4';
import { setting5Icon } from './setting-5';
import { settingIcon } from './setting';
import { settingsIcon } from './settings';
import { toggleOffCircleIcon } from './toggle-off-circle';
import { toggleOffIcon } from './toggle-off';
import { toggleOnCircleIcon } from './toggle-on-circle';
import { toggleOnIcon } from './toggle-on';
export const settingsIcons = [candle2Icon, candleIcon, category2Icon, categoryIcon, menuIcon, more2Icon, moreIcon, setting2Icon, setting3Icon, setting4Icon, setting5Icon, settingIcon, settingsIcon, toggleOffCircleIcon, toggleOffIcon, toggleOnCircleIcon, toggleOnIcon];
