import { bankIcon } from './bank';
import { building3Icon } from './building-3';
import { building4Icon } from './building-4';
import { buildingIcon } from './building';
import { buildings2Icon } from './buildings-2';
import { buildingsIcon } from './buildings';
import { bulidingIcon } from './buliding';
import { courthouseIcon } from './courthouse';
import { hospitalIcon } from './hospital';
import { house2Icon } from './house-2';
import { houseIcon } from './house';
export const buildingIcons = [bankIcon, building3Icon, building4Icon, buildingIcon, buildings2Icon, buildingsIcon, bulidingIcon, courthouseIcon, hospitalIcon, house2Icon, houseIcon];
