import { lampChargeIcon } from './lamp-charge';
import { lampOnIcon } from './lamp-on';
import { lampSlashIcon } from './lamp-slash';
import { notification1Icon } from './notification-1';
import { notificationBingIcon } from './notification-bing';
import { notificationCircleIcon } from './notification-circle';
import { notificationFavoriteIcon } from './notification-favorite';
import { notificationStatusIcon } from './notification-status';
import { notificationIcon } from './notification';
export const notificationsIcons = [lampChargeIcon, lampOnIcon, lampSlashIcon, notification1Icon, notificationBingIcon, notificationCircleIcon, notificationFavoriteIcon, notificationStatusIcon, notificationIcon];
